#Promting input from the user. n1 = float(input("Enter the First Number: ")) n2 = float(input("Enter the Second Number: "))
#addition. print("{56} + {3} = ". format(n1, n2)) ...
#subtraction. print("{45} - {7} = ". ...
#multiplication. print("{23} * {9} = ". ...
#division. print("{44} / {4"} = ".
